FROM nixyslab/nxs-backup-bin AS bin

FROM debian:11-slim

RUN apt update \
    && apt install -yq \
      lsb-release \
      wget \
      gnupg \
    && wget -O /tmp/mcc.deb https://downloads.mysql.com/archives/get/p/23/file/mysql-community-client_5.7.42-1debian10_amd64.deb \
    && apt -yq purge wget  && apt -yq autoremove && apt -yq install /tmp/mcc.deb \
    && rm /tmp/mcc.deb \
    && apt clean \
    && rm -rf /var/lib/apt/lists/*

COPY --from=bin /nxs-backup /usr/local/bin/nxs-backup

CMD nxs-backup start
