FROM alpine AS builder

ARG VERSION

RUN case "$(apk --print-arch)" in \
      x86_64) export ARCH='amd64' ;; \
      aarch64) export ARCH='arm64' ;; \
      armv7) export ARCH='arm' ;; \
    esac; \
    wget -O /tmp/nxsb.tgz "https://github.com/nixys/nxs-backup/releases/download/$VERSION/nxs-backup-$ARCH.tar.gz"; \
    tar xf /tmp/nxsb.tgz


FROM scratch

COPY --from=builder /nxs-backup /nxs-backup
ENTRYPOINT ["/nxs-backup"]
