FROM nixyslab/nxs-backup-bin AS bin

FROM alpine:3

RUN apk update --no-cache && apk add --no-cache tar mysql-client mariadb-backup postgresql18-client mongodb-tools redis
COPY --from=bin /nxs-backup /usr/local/bin/nxs-backup

VOLUME /etc/nxs-backup
VOLUME /var/nxs-backup

CMD nxs-backup start
