#!/bin/sh -e

. /usr/share/debconf/confmodule
db_version 2.0 || [ $? -lt 30 ]

if [ "$1" = "configure" ]; then

	chown -R root: /etc/nxs-backup
	chmod 750 /etc/nxs-backup
	chmod 750 /etc/nxs-backup/conf.d
	chmod 0640 /etc/nxs-backup/nxs-backup.conf

	chmod 750 /var/log/nxs-backup
fi

db_stop

exit 0
